POST http://localhost:8080/api/heroes HTTP/1.1
content-type: application/json

{
    "name": "Eric"
}
###
PUT http://localhost:8080/api/heroes/1 HTTP/1.1
content-type: application/json

{
    "name": "John"
}
###
GET  http://localhost:8080/api/heroes HTTP/1.1
###
GET  http://localhost:8080/api/heroes/15 HTTP/1.1
###
DELETE  http://localhost:8080/api/heroes/1 HTTP/1.1
###
GET http://localhost:8080/api/heroes/search?name=a HTTP/1.1